// <auto-generated />
namespace Project_G3.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Error1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Error1));
        
        string IMigrationMetadata.Id
        {
            get { return "202105031156411_Error1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
