// <auto-generated />
namespace Project_G3.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Base : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Base));
        
        string IMigrationMetadata.Id
        {
            get { return "202105181232597_Base"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
